#!/bin/bash
AMBROSIAHOME="$HOME"
AMBROSIASCRIPTS_LOC="$AMBROSIAHOME/scripts"
AMBROSIA_LOC="$AMBROSIAHOME"
AMBROSIA_POV_LOC="$AMBROSIAHOME/scripts"
AMBROSIA_VERSION="1"
BASH_LOC=`type -p bash`
CONVERT_LOC=`type -p convert`
FFMPEG_LOC=`type -p ffmpeg`
LESS_LOC=`type -p less`
MAKEMOVIE=`type -p ffmpeg`
MOVIEVIEW=`type -p ambrosia-open`
OPEN_LOC=`type -p ambrosia-open`
OS="Linux"
POVRAY_LOC=`type -p povray`
TEXTVIEW=`type -p ambrosia-open`
VIEW=`type -p ambrosia-open`

PATH="$AMBROSIASCRIPTS_LOC":/usr/bin:/bin:$PATH

